### PR TITLE
Set module entry file to correct build path

### PR DESCRIPTION
**Pull request by jkva**
This addresses the incorrect module entry file as discussed in #4.

### CODE REVIEW

**Comment by jkva** [comment]
@christian-bromann Any chance of incorporating this small change into a module release?

**Comment by christian-bromann** [comment]
@jkva I am not longer with Sauce Labs anymore and in the process to get this repository transferred to my account.

@diemol any updates?

**Comment by diemol** [comment]
Still waiting for legal.

Why don't you make pull requests if needed and I am happy to merge them for you in the meantime?

**Comment by diemol** [comment]
Did not see **this** was a pull request, 🤦 

If you approve the PR, @christian-bromann, I can merge it.

**Comment by christian-bromann** [comment]
Yes, please merge and release as `patch`, thanks!

**Pull request merged**
